profile/urls.py
from django.urls import path
from .import views


app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('about/', views.about, name='about')

]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profile.urls')),
]

profile/models.py
from django.db import models

# Create your models here.

profile/views.py
from django.shortcuts import render

def profile(request):
    return render(request, 'profile.html')

def about(request):
    return render(request, 'about.html')

# Create your views here.

profile/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title> Muhammad Alfath Fiqhya Amrinagara</title>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
            $(function() {
                $("#accordionPendidikan").accordion({header: "> div > h3"})
                .sortable({
                    axis: "y",
                    handle: "h3",
                    stop: function(event, ui){
                        ui.item.children("h3").triggerHandler("focusout");
                        $(this).accordion("refresh");
                    }
                });
            });
        </script>
        <style>
            *{padding: 0; margin: 0;}
            p.solid {border-style: solid;}
            h1 {text-align: center;}
            p {text-align: center;}
            div {text-align: center;}
            h2 {text-align: center;}
            h3 {background: white; padding: 5px; border: 1px solid #ccc;}
            #accordionPendidikan{width: 500px; margin: auto;}
            img {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            body  {
                background-color: rgb(51, 54, 54);
            }
            .ap{
                background: yellow;
                padding: 20px;
            }
            .bio{
            width: 101%;
            margin-top: 0%;
            margin-right: -100;
            background-color: #31CD7A;
            border-style: solid;
            border-color: rgb(0, 0, 0);
            padding: 20px 0;
            }

            .pendidikan{
            width: 101%;
            margin-top: 0%;
            margin-right: -100;
            background-color: #31CD7A;
            border-style: solid;
            border-color: rgb(0, 0, 0);
            padding: 20px 0;
            }

            .kontak{
            background-color: #000000;
            text-align: center;
            padding: 20px 0;
            }
        </style>
    </head>

    <body>
        <div style="background-color: black;">
        <ul class="nav justify-content-end" id="pills-tab" role="tablist">
            <li class="nav-item" role="presentation">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="{% url 'profile:profile' %}" role="tab" aria-controls="pills-home" aria-selected="true">Home</a>
            </li>
            <li class="nav-item" role="presentation">
            <a class="nav-link" id="pills-about-tab" data-toggle="pill" href="{% url 'profile:about' %}" role="tab" aria-controls="pills-about" aria-selected="false">about</a>
            
            </li>
        </ul>
    </div>

        <header>
            <h1 style="color:rgb(255, 255, 255)"> MUHAMMAD ALFATH FIQHYA AMRINAGARA</h1>   
        </header>

    <img src="{% static 'FR37.jpg' %}" width="250" height="400" border= "5">
    <h2 style="color:rgb(255, 255, 255)"> BIO</h2>
    <div class="bio">    
        <p style="font-family:verdana"> Nama: Muhammad Alfath Fiqhya Amrinagara (Alfath)</p>
        <p style="font-family:verdana">NPM: 1906299036</p>
        <p style="font-family:verdana">Angkatan: 2019</p>
        <p style="font-family:verdana">Hobby: Mendengarkan Musik</p>
        <p style="font-family:verdana"> Description: Seseorang Yang Suka Membuat Orang Lain Bahagia</p>
    </div>

    <h2 style="color:rgb(255, 255, 255)"> PENDIDIKAN</h2>

    <!--
    <div class="pendidikan">
    <p style="font-family:verdana">2007-2013 : Global Islamic School</p>
    <p style="font-family:verdana">2013-2016 : MTsN 7 Jakarta</p>
    <p style="font-family:verdana">2016-2019 : MAN 13 Jakarta</p>
    <p style="font-family:verdana">2019-Sekarang : Fakultas Ilmu Komputer Universitas Indonesia</p>
    </div>
    -->
    <div class="pendidikan">
    <div id="accordionPendidikan">
        <div class="group">
            <h3>Pendidikan 1</h3>
            <div class="ap">
                <p>2007-2013 : Global Islamic School</p>
            </div>
        </div>
        <div class="group">
            <h3>Pendidikan 2</h3>
            <div class="ap">
                <p>2013-2016 : MTsN 7 Jakarta</p>
            </div>
        </div>
        <div class="group">
            <h3>Pendidikan 3</h3>
            <div class="ap">
                <p>2016-2019 : MAN 13 Jakarta</p>
            </div>
        </div>
        <div class="group">
            <h3>Pendidikan 4</h3>
            <div class="ap">
                <p>2019-Sekarang : Fakultas Ilmu Komputer Universitas Indonesia</p>
            </div>
        </div>
    </div>
    </div>

    <div class="kontak">
        <h1 style="color:rgb(253, 252, 252)">Contact</h1>
        <p style="text-aligh: center;">
            <a href="https://www.instagram.com/alfathfiqhya">
                <img src="/static/639b3dafb544d6f061fcddd2d6686ddb.png" class="img-fluid" alt="Responsive image" width="100" height="200">
            </a>
        </p>
        <p class="cr" style="color:rgb(253, 252, 252)">Copyright 2020 Alfath, All right reserved</p>

    </div>
</body>
</html>

profile/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        
        <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        
        <title> Muhammad Alfath Fiqhya Amrinagara</title>
        <style>
            .salam {
                background-color: #31CD7A;
                text-align: center;
            }

            .about {
                background-color: #010201;
            }
            
            .pendidikan{
                background-color: #31CD7A;
                text-align: center;
            }

            .kontak{
                background-color: #010201;
                text-align: center;
            }

        </style>

    <body>
        <div style="background-color: black;">
            <ul class="nav justify-content-end" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                <a class="nav-link"href="{% url 'profile:profile' %}" >Home</a>
                </li>
                <li class="nav-item" role="presentation">
                <a class="nav-link"  href="{% url 'profile:about' %}" >About</a>
            </li>
            </ul>
        </div>

        <div class="salam">
            <h1 style="color:rgb(12, 9, 9)"> I'm</h1>   
            <h1 style="color:rgb(12, 9, 9)"> MUHAMMAD ALFATH FIQHYA AMRINAGARA</h1>   
            <h1 style="color:rgb(12, 9, 9)"> Welcome to my web</h1>
        </div>

        <div class="about">
            <table class="table table-borderless">
                <tbody>
                    <th>
                        <img src="{% static 'FR37.jpg' %}" width="250" height="350" border= "5" >
                    </th>
                    <td style="color:rgb(253, 252, 252); margin-left: auto; margin-right: auto;">University of Indonesia Student Faculty of Computer Science</td>
                </tbody>
            </table>
        </div>

        <div class="pendidikan">
            <h1>Education</h1>
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <th>
                            <img src="/static/Logo-Madrasah-MI-Mts-dan-MA-Warna.png" class="img-fluid" alt="Responsive image" width="100" height="200">
                        </th>
                        <th>
                            <img src="/static/Logo-Madrasah-MI-Mts-dan-MA-Warna.png" class="img-fluid" alt="Responsive image" width="100" height="200">
                        </th>
                        <th>
                            <img src="/static/makara-ui-fasilkom.png" class="img-fluid" alt="Responsive image" width="100" height="200">
                        </th>
                    </tr>
                    <tr>
                        <td style="font-weight: Bolt;">2013 - 2016</td>
                        <td style="font-weight: Bolt;">2016 - 2019</td>
                        <td style="font-weight: Bolt;">2019 - NOW</td>
                    </tr>
                    <tr>
                        <td style="font-weight: Bolt;">MTsN 7 Jakarta</td>
                        <td style="font-weight: Bolt;">MAN 13 Jakarta</td>
                        <td style="font-weight: Bolt;">Universitas Indonesia</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="kontak">
            <h1 style="color:rgb(253, 252, 252)">Contact</h1>
            <p style="text-aligh: center;">
                <a href="https://www.instagram.com/alfathfiqhya">
                    <img src="/static/639b3dafb544d6f061fcddd2d6686ddb.png" class="img-fluid" alt="Responsive image" width="100" height="200">
                </a>
            </p>
            <p class="cr" style="color:rgb(253, 252, 252)">Copyright 2020 Alfath, All right reserved</p>

        </div>

    </body>